#!/usr/bin/env bun
/**
 * Build for Android (aarch64)
 *
 * 1. Generates the models-snapshot.js
 * 2. Loads migrations
 * 3. Bundles using Bun.build() with compile targeting the host platform
 * 4. Extracts the module graph from the compiled binary
 * 5. Appends it to Android bun binary to create the final standalone
 */

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { createSolidTransformPlugin } from "@opentui/solid/bun-plugin"

const OPENCODE_DIR = process.env.OPENCODE_DIR || (() => { throw new Error("OPENCODE_DIR not set") })()
const ANDROID_BUN = process.env.ANDROID_BUN || (() => { throw new Error("ANDROID_BUN not set") })()
const OUTPUT_DIR = process.env.OUTPUT_DIR || (() => { throw new Error("OUTPUT_DIR not set") })()

if (!fs.existsSync(ANDROID_BUN)) {
  console.error("Android bun binary not found at:", ANDROID_BUN)
  process.exit(1)
}

process.chdir(OPENCODE_DIR)

const VERSION = process.env.APP_VERSION || "1.0.0"
const CHANNEL = "latest"
const APP_NAME = process.env.APP_NAME || "opencode"
const APP_BINARY = process.env.APP_BINARY || "opencode"
const APP_IDENTITY = process.env.APP_IDENTITY || ""

console.log(`Building ${APP_NAME} v${VERSION} for Android aarch64`)

// Step 1: Generate models-snapshot.js
console.log("\n=== Step 1: Generating models-snapshot.js ===")

const modelsPath = process.env.APP_MODELS_JSON
let modelsData: string = ""
if (modelsPath) {
  console.log(`Using custom models from: ${modelsPath}`)
  modelsData = await Bun.file(modelsPath).text()
} else {
  const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
  if (process.env.MODELS_DEV_API_JSON) {
    modelsData = await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  } else {
    console.log(`Fetching from ${modelsUrl}/api.json ...`)
    let fetchErr: Error | null = null
    for (let attempt = 1; attempt <= 3; attempt++) {
      try {
        const resp = await fetch(`${modelsUrl}/api.json`, { signal: AbortSignal.timeout(15000) })
        if (!resp.ok) throw new Error(`HTTP ${resp.status}`)
        modelsData = await resp.text()
        fetchErr = null
        break
      } catch (err: any) {
        fetchErr = err
        console.error(`  Attempt ${attempt}/3 failed: ${err.message}`)
        if (attempt < 3) await new Promise(r => setTimeout(r, 2000 * attempt))
      }
    }
    if (fetchErr) {
      console.error(`ERROR: Failed to fetch models after 3 attempts: ${fetchErr.message}`)
      process.exit(1)
    }
  }
}
await Bun.write(
  path.join(OPENCODE_DIR, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(OPENCODE_DIR, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")

// Step 2: Load migrations
console.log("\n=== Step 2: Loading migrations ===")
const migrationDirs = (
  await fs.promises.readdir(path.join(OPENCODE_DIR, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{14}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(OPENCODE_DIR, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(Number(match[1]), Number(match[2]) - 1, Number(match[3]), Number(match[4]), Number(match[5]), Number(match[6]))
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

// Step 3: Build with Bun.build() --compile for the HOST platform
console.log("\n=== Step 3: Bundling ===")

const plugin = createSolidTransformPlugin()

const localPath = path.resolve(OPENCODE_DIR, "node_modules/@opentui/core/parser.worker.js")
const rootPath = path.resolve(OPENCODE_DIR, "../../node_modules/@opentui/core/parser.worker.js")
let parserWorkerResolved: string
try {
  parserWorkerResolved = fs.realpathSync(fs.existsSync(localPath) ? localPath : rootPath)
} catch {
  parserWorkerResolved = require.resolve("@opentui/core/parser.worker.js")
}
console.log(`Parser worker: ${parserWorkerResolved}`)

const workerPath = "./src/cli/cmd/tui/worker.ts"
const bunfsRoot = "/$bunfs/root/"
const workerRelativePath = path.relative(OPENCODE_DIR, parserWorkerResolved).replaceAll("\\", "/")

await $`rm -rf ${OUTPUT_DIR}`
await $`mkdir -p ${OUTPUT_DIR}`

const hostBinaryPath = path.join(OUTPUT_DIR, `${APP_BINARY}-host`)

console.log("Building standalone binary for host platform...")
const result = await Bun.build({
  conditions: ["browser"],
  tsconfig: "./tsconfig.json",
  plugins: [plugin],
  compile: {
    autoloadBunfig: false,
    autoloadDotenv: false,
    autoloadTsconfig: true,
    autoloadPackageJson: true,
    outfile: hostBinaryPath,
    execArgv: [`--user-agent=${APP_BINARY}/${VERSION}`, "--use-system-ca", "--"],
  },
  entrypoints: ["./src/index.ts", parserWorkerResolved, workerPath],
  define: {
    OPENCODE_VERSION: `'${VERSION}'`,
    OPENCODE_MIGRATIONS: JSON.stringify(migrations),
    OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
    OPENCODE_WORKER_PATH: workerPath,
    OPENCODE_CHANNEL: `'${CHANNEL}'`,
    OPENCODE_LIBC: "",
  },
})

if (!result.success) {
  console.error("Build failed:")
  for (const msg of result.logs) console.error(msg)
  process.exit(1)
}

console.log(`Host standalone binary: ${hostBinaryPath}`)

// Step 4: Extract module graph from host binary
console.log("\n=== Step 4: Extracting module graph ===")

const hostBinary = await Bun.file(hostBinaryPath).arrayBuffer()
const hostBytes = new Uint8Array(hostBinary)

const TRAILER_STR = "\n---- Bun! ----\n"
const TRAILER_LEN = TRAILER_STR.length
const OFFSETS_SIZE_CONST = 32

const trailerBuf = Buffer.from(TRAILER_STR)
const searchBuf = Buffer.from(hostBytes.buffer, hostBytes.byteOffset, hostBytes.length)
const trailerEnd = hostBytes.length - 8
const expectedTrailerStart = trailerEnd - TRAILER_LEN

const foundTrailer = searchBuf.compare(trailerBuf, 0, TRAILER_LEN, expectedTrailerStart, trailerEnd) === 0

if (!foundTrailer) {
  console.error("ERROR: Bun standalone trailer not found")
  process.exit(1)
}

const offsetsStart = expectedTrailerStart - OFFSETS_SIZE_CONST
const offsetsByteCount = Number(searchBuf.readBigUInt64LE(offsetsStart))
const moduleGraphSize = offsetsByteCount + OFFSETS_SIZE_CONST + TRAILER_LEN
const hostBunSize = hostBytes.length - 8 - moduleGraphSize

console.log(`Host binary size: ${hostBytes.length}`)
console.log(`Module graph size: ${moduleGraphSize}`)

if (hostBunSize <= 0) {
  console.error(`ERROR: Derived host bun size is ${hostBunSize}`)
  process.exit(1)
}

const moduleGraphBytes = hostBytes.slice(hostBunSize, hostBytes.length - 8)
console.log(`Module graph extracted: ${moduleGraphBytes.length} bytes`)

// Step 5: Patch module graph for Android
console.log("\n=== Step 5: Patching module graph for Android ===")

const mgTrailer = "\n---- Bun! ----\n"
const mgTrailerBuf = Buffer.from(mgTrailer)
const OFFSETS_SIZE = 32

const mgBuf = Buffer.from(moduleGraphBytes)
const trailerPosInMg = mgBuf.lastIndexOf(mgTrailerBuf)
if (trailerPosInMg < 0) throw new Error("Trailer not found in module graph!")

const mgOffsetsStart = trailerPosInMg - OFFSETS_SIZE
const byteCount = Number(mgBuf.readBigUInt64LE(mgOffsetsStart))
const modOff = mgBuf.readUInt32LE(mgOffsetsStart + 8)
const modLen = mgBuf.readUInt32LE(mgOffsetsStart + 12)

console.log(`byte_count=${byteCount}, modules_ptr=(${modOff},${modLen})`)

// Patch undici reference for Android bun compat
const UNDICI_SEARCH  = Buffer.from('__reExport(exports_Undici, undici)')
const UNDICI_REPLACE = Buffer.from('__reExport(exports_Undici, Undici)')
console.log(`\nPatch: undici->Undici (same size)`)

let undiciPatchCount = 0
let searchPos = 0
const strDataRegion = mgBuf.slice(0, modOff)
while (true) {
  const pos = strDataRegion.indexOf(UNDICI_SEARCH, searchPos)
  if (pos < 0) break
  console.log(`  Found at offset ${pos}`)
  UNDICI_REPLACE.copy(mgBuf, pos)
  undiciPatchCount++
  searchPos = pos + UNDICI_SEARCH.length
}
if (undiciPatchCount === 0) {
  console.error("WARNING: undici pattern not found — skipping")
} else {
  console.log(`  Patched ${undiciPatchCount} occurrence(s)`)
}

var finalModuleGraph = mgBuf.slice(0, trailerPosInMg + mgTrailerBuf.length)
console.log(`Module graph size: ${finalModuleGraph.length} bytes`)

// Step 6: Create Android standalone binary
console.log("\n=== Step 6: Creating Android standalone binary ===")

const androidBunBytes = new Uint8Array(await Bun.file(ANDROID_BUN).arrayBuffer())
const androidBunSize = androidBunBytes.length
console.log(`Android bun size: ${androidBunSize}`)

const newTotalByteCount = androidBunSize + finalModuleGraph.length + 8
const outputSize = androidBunSize + finalModuleGraph.length + 8
const output = new Uint8Array(outputSize)

output.set(androidBunBytes, 0)
output.set(new Uint8Array(finalModuleGraph.buffer, finalModuleGraph.byteOffset, finalModuleGraph.length), androidBunSize)

const totalView = new DataView(output.buffer, outputSize - 8, 8)
totalView.setUint32(0, newTotalByteCount & 0xFFFFFFFF, true)
totalView.setUint32(4, Math.floor(newTotalByteCount / 0x100000000), true)

const androidOutputPath = path.join(OUTPUT_DIR, APP_BINARY)
await Bun.write(androidOutputPath, output)
fs.chmodSync(androidOutputPath, 0o755)

console.log(`\nAndroid standalone binary: ${androidOutputPath}`)
console.log(`Size: ${(outputSize / 1024 / 1024).toFixed(1)} MB`)

// Verify
const verifyBytes = new Uint8Array(await Bun.file(androidOutputPath).arrayBuffer())
const verifyView = new DataView(verifyBytes.buffer, verifyBytes.length - 8, 8)
const verifyTotal = verifyView.getUint32(0, true) + verifyView.getUint32(4, true) * 0x100000000
console.log(`Verification: total_byte_count=${verifyTotal}, file_size=${verifyBytes.length}, match=${verifyTotal === verifyBytes.length}`)

const elfMagic = String.fromCharCode(verifyBytes[0], verifyBytes[1], verifyBytes[2], verifyBytes[3])
console.log(`ELF magic: ${elfMagic === "\x7fELF" ? "OK" : "INVALID"}`)

console.log("\n=== Build complete! ===")
console.log(`Output: ${androidOutputPath}`)
